### PR TITLE
Add Docker configuration

### PR DESCRIPTION
**Pull request by cristinaleonr**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/packet-test/2)

### CODE REVIEW

**Review by robertodauria — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/packet-test/2)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Review by robertodauria — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/packet-test/2#-:-NvlGdE4AXrN_kT7vuJk:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Review by robertodauria — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/packet-test/2)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`build.sh` line 4 at r1](https://reviewable.io/reviews/m-lab/packet-test/2#-NvlGfti8SDG2FHb5VNK:-NvlGfti8SDG2FHb5VNL:b-y4uj6u) ([raw file](https://github.com/m-lab/packet-test/blob/f4981dd7756638450a3e2f66a27d89212c08f85f/build.sh#L4)):*
> ```Shell
> set -ex
> 
> go build -v ./cmd/server
> ```

Nit: newline
___
*[`Dockerfile` line 16 at r1](https://reviewable.io/reviews/m-lab/packet-test/2#-NvlGi1j2tTQwk2nrRng:-NvlGi1j2tTQwk2nrRnh:b-y4uj6u) ([raw file](https://github.com/m-lab/packet-test/blob/f4981dd7756638450a3e2f66a27d89212c08f85f/Dockerfile#L16)):*
> ```Dockerfile
> COPY --from=build /packet-test/server /packet-test/
> 
> ENTRYPOINT ["./server"]
> ```

Nit: newline

**Review by cristinaleonr — COMMENTED** [review]
Thank you!

> *[Reviewable](https://reviewable.io/reviews/m-lab/packet-test/2#-:-NvlYcg25HHHTIKO3PPv:b-9755fn)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @robertodauria)

___
*[`build.sh` line 4 at r1](https://reviewable.io/reviews/m-lab/packet-test/2#-NvlGfti8SDG2FHb5VNK:-NvlY_RHC-bg5_XVsfeA:b-a2ujfl) ([raw file](https://github.com/m-lab/packet-test/blob/f4981dd7756638450a3e2f66a27d89212c08f85f/build.sh#L4)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: newline
</blockquote></details>

Changed.
___
*[`Dockerfile` line 16 at r1](https://reviewable.io/reviews/m-lab/packet-test/2#-NvlGi1j2tTQwk2nrRng:-NvlYaYe-7SjdPPqgh3w:b-a2ujfl) ([raw file](https://github.com/m-lab/packet-test/blob/f4981dd7756638450a3e2f66a27d89212c08f85f/Dockerfile#L16)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: newline
</blockquote></details>

Changed.

**Pull request merged**
